# Claude Code Agent - GitHub Actions Workflow
#
# Required GitHub Repository Variables (Settings > Secrets and variables > Actions > Variables):
#   AWS_ACCOUNT_ID  - Your AWS account ID (e.g., 123456789012)
#   AWS_REGION      - AWS region (e.g., us-west-2)
#   PROJECT         - Project name used for resource naming (e.g., myproject)
#   CLAUDE_MODEL    - Claude model to use (e.g., opus)
#
# Required AWS Resources:
#   - IAM OIDC Provider for GitHub Actions
#   - IAM Role with trust policy for GitHub OIDC
#   - Secrets Manager secret with ANTHROPIC_API_KEY (and optionally OPENAI_API_KEY)
#   - S3 bucket for Pulumi/Terraform state (optional, for IaC projects)
#
# Pulumi Setup (used in this example):
#   pulumi config set aws:region $AWS_REGION
#   pulumi login s3://${PROJECT}-pulumi-state-${AWS_ACCOUNT_ID}
#
# Terraform Equivalent Setup:
#   terraform {
#     backend "s3" {
#       bucket         = "${var.project}-terraform-state-${var.aws_account_id}"
#       key            = "terraform.tfstate"
#       region         = var.aws_region
#       encrypt        = true
#       dynamodb_table = "${var.project}-terraform-locks"  # Optional: for state locking
#     }
#   }

name: Claude Code Agent

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

permissions:
  id-token: write # Required for OIDC
  contents: write # Required to push changes
  issues: write # Required to comment on issues
  pull-requests: write # Required to create PRs

jobs:
  claude-agent:
    runs-on: ubuntu-latest
    # Security: Only allow repo collaborators to trigger the agent
    # Prevents unauthorized users from invoking Claude with write permissions
    # - Labeled: trust labeler (requires triage+ permission), verify it's the claude-agent label
    # - Opened: check issue author association
    # - Comment: check commenter association AND require @claude-agent mention
    if: >-
      (github.event.action == 'labeled' &&
       github.event.label.name == 'claude-agent') ||
      (github.event.action == 'opened' &&
       contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.issue.author_association)) ||
      (github.event_name == 'issue_comment' &&
       contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association) &&
       contains(github.event.comment.body, '@claude-agent'))

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better context

      - name: Configure AWS credentials
        # Uses OIDC to assume IAM role - no long-lived credentials needed
        # Pulumi IAM Role Setup:
        #   aws.iam.Role with assumeRolePolicy trusting token.actions.githubusercontent.com
        #
        # Terraform Equivalent:
        #   resource "aws_iam_openid_connect_provider" "github" {
        #     url             = "https://token.actions.githubusercontent.com"
        #     client_id_list  = ["sts.amazonaws.com"]
        #     thumbprint_list = ["ffffffffffffffffffffffffffffffffffffffff"]
        #   }
        #
        #   resource "aws_iam_role" "github_actions" {
        #     name = "github-actions-${var.project}-role"
        #     assume_role_policy = jsonencode({
        #       Version = "2012-10-17"
        #       Statement = [{
        #         Effect = "Allow"
        #         Principal = { Federated = aws_iam_openid_connect_provider.github.arn }
        #         Action = "sts:AssumeRoleWithWebIdentity"
        #         Condition = {
        #           StringEquals = { "token.actions.githubusercontent.com:aud" = "sts.amazonaws.com" }
        #           StringLike   = { "token.actions.githubusercontent.com:sub" = "repo:YOUR_ORG/YOUR_REPO:*" }
        #         }
        #       }]
        #     })
        #   }
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-${{ vars.PROJECT }}-role
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: claude-code-action

      - name: Fetch secrets from AWS Secrets Manager
        # Secrets are stored in AWS Secrets Manager, not GitHub Secrets
        # This provides centralized secret management and rotation
        #
        # Pulumi Secret Setup:
        #   aws.secretsmanager.Secret with secretString containing JSON
        #
        # Terraform Equivalent:
        #   resource "aws_secretsmanager_secret" "credentials" {
        #     name = "${var.project}-credentials"
        #   }
        #
        #   resource "aws_secretsmanager_secret_version" "credentials" {
        #     secret_id = aws_secretsmanager_secret.credentials.id
        #     secret_string = jsonencode({
        #       ANTHROPIC_API_KEY = var.anthropic_api_key
        #       OPENAI_API_KEY    = var.openai_api_key  # Optional
        #     })
        #   }
        id: secrets
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value \
            --secret-id ${{ vars.PROJECT }}-credentials \
            --region ${{ vars.AWS_REGION }} \
            --query SecretString \
            --output text)

          # Export secrets as environment variables (masked)
          echo "::add-mask::$(echo $SECRET_JSON | jq -r '.OPENAI_API_KEY')"
          echo "::add-mask::$(echo $SECRET_JSON | jq -r '.ANTHROPIC_API_KEY')"

          echo "OPENAI_API_KEY=$(echo $SECRET_JSON | jq -r '.OPENAI_API_KEY')" >> $GITHUB_ENV
          echo "ANTHROPIC_API_KEY=$(echo $SECRET_JSON | jq -r '.ANTHROPIC_API_KEY')" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure Pulumi S3 backend
        # Pulumi uses S3 for state storage
        #
        # Terraform Equivalent (configure in terraform block instead):
        #   export TF_BACKEND_BUCKET="${{ vars.PROJECT }}-terraform-state-${{ vars.AWS_ACCOUNT_ID }}"
        #   terraform init -backend-config="bucket=$TF_BACKEND_BUCKET"
        run: |
          # Configure Pulumi to use S3 backend for state storage
          echo "PULUMI_BACKEND_URL=s3://${{ vars.PROJECT }}-pulumi-state-${{ vars.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ vars.AWS_REGION }}" >> $GITHUB_ENV

      - name: Run Claude Code Agent
        uses: anthropics/claude-code-action@v1
        env:
          OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
          PULUMI_BACKEND_URL: ${{ env.PULUMI_BACKEND_URL }}
          AWS_REGION: ${{ env.AWS_REGION }}
        with:
          anthropic_api_key: ${{ env.ANTHROPIC_API_KEY }}
          trigger_phrase: "@claude-agent"
          label_trigger: "claude-agent"
          claude_args: |
            --model ${{ vars.CLAUDE_MODEL }}
            --allowedTools "Edit,MultiEdit,Glob,Grep,LS,Read,Write,Bash(git:*),Bash(gh pr create:*),Bash(gh pr list:*)"
            --customInstructions "After completing your work on an issue:
            1. Commit all changes with git
            2. Create a pull request using: gh pr create --title '...' --body 'Resolves #<issue>' --label 'codex-review'
            3. The PR will be automatically reviewed by Codex
            4. If Codex finds HIGH severity issues, you may be asked to fix them"
