# Codex Code Review - GitHub Actions Workflow
#
# Required GitHub Repository Variables (Settings > Secrets and variables > Actions > Variables):
#   AWS_ACCOUNT_ID  - Your AWS account ID (e.g., 123456789012)
#   AWS_REGION      - AWS region (e.g., us-west-2)
#   PROJECT         - Project name used for resource naming (e.g., myproject)
#   CODEX_MODEL     - Codex model to use (e.g., gpt-5.1-codex-max)
#   CODEX_EFFORT    - Reasoning effort level (low, medium, high, xhigh)
#
# Required AWS Resources:
#   - IAM OIDC Provider for GitHub Actions (same as claude-code-action)
#   - IAM Role with trust policy for GitHub OIDC
#   - Secrets Manager secret with OPENAI_API_KEY

name: Codex Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # Only PRs from Claude agent branches

jobs:
  codex-review:
    # Only run on PRs from claude/* branches in the same repo (block forks to prevent credential theft)
    if: >-
      startsWith(github.event.pull_request.head.ref, 'claude/') &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read
      pull-requests: write

    steps:
      - name: Checkout PR merge commit
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-${{ vars.PROJECT }}-role
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: codex-review-action

      - name: Fetch OpenAI API key from AWS Secrets Manager
        id: secrets
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value \
            --secret-id ${{ vars.PROJECT }}-credentials \
            --region ${{ vars.AWS_REGION }} \
            --query SecretString \
            --output text)

          echo "::add-mask::$(echo $SECRET_JSON | jq -r '.OPENAI_API_KEY')"
          echo "OPENAI_API_KEY=$(echo $SECRET_JSON | jq -r '.OPENAI_API_KEY')" >> $GITHUB_ENV

      - name: Run Codex Code Review
        id: codex_review
        uses: openai/codex-action@v1
        with:
          openai-api-key: ${{ env.OPENAI_API_KEY }}
          model: ${{ vars.CODEX_MODEL }}
          effort: ${{ vars.CODEX_EFFORT }}
          safety-strategy: drop-sudo
          prompt: |
            Review PR #${{ github.event.pull_request.number }} for code quality, bugs, and security issues.

            Focus on:
            1. **HIGH severity issues** - Security vulnerabilities, data loss, critical bugs
            2. **MEDIUM severity issues** - Logic errors, performance issues, bad patterns
            3. **LOW severity issues** - Style, minor improvements

            Changes to review:
            git log --oneline ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}
            git diff ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}

            **Output format:**
            ```json
            {
              "high_severity_count": <number>,
              "high_severity_issues": ["issue 1", "issue 2"],
              "medium_severity_count": <number>,
              "medium_severity_issues": ["issue 1"],
              "low_severity_count": <number>,
              "summary": "Overall assessment",
              "recommendation": "APPROVE | REQUEST_CHANGES"
            }
            ```

            Be thorough and use maximum reasoning effort.

      - name: Parse Codex Review Results
        id: parse_results
        env:
          # Pass output via env var to prevent shell injection
          CODEX_RAW_OUTPUT: ${{ steps.codex_review.outputs.final-message }}
        run: |
          # Write output to file safely (avoids shell injection)
          printf '%s' "$CODEX_RAW_OUTPUT" > /tmp/codex_output_raw.txt

          # Save raw output for later steps via GITHUB_ENV
          {
            echo "CODEX_OUTPUT<<CODEX_EOF_MARKER"
            cat /tmp/codex_output_raw.txt
            echo "CODEX_EOF_MARKER"
          } >> "$GITHUB_ENV"

          # Strip markdown code fences if present (```json ... ```)
          sed -n '/^```json/,/^```$/p' /tmp/codex_output_raw.txt | sed '1d;$d' > /tmp/codex_json.txt
          # If no fenced block found, try raw content
          if [ ! -s /tmp/codex_json.txt ]; then
            cp /tmp/codex_output_raw.txt /tmp/codex_json.txt
          fi

          # Attempt to parse JSON - treat failures as review failures
          if ! HIGH_COUNT=$(jq -r '.high_severity_count' /tmp/codex_json.txt 2>/dev/null); then
            echo "::error::Failed to parse Codex output as JSON"
            echo "parse_failed=true" >> $GITHUB_OUTPUT
            echo "high_severity_count=-1" >> $GITHUB_OUTPUT
            echo "medium_severity_count=-1" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Validate we got a number
          if ! [[ "$HIGH_COUNT" =~ ^[0-9]+$ ]]; then
            echo "::error::high_severity_count is not a valid number: $HIGH_COUNT"
            echo "parse_failed=true" >> $GITHUB_OUTPUT
            echo "high_severity_count=-1" >> $GITHUB_OUTPUT
            echo "medium_severity_count=-1" >> $GITHUB_OUTPUT
            exit 0
          fi

          MEDIUM_COUNT=$(jq -r '.medium_severity_count // 0' /tmp/codex_json.txt)
          RECOMMENDATION=$(jq -r '.recommendation // "UNKNOWN"' /tmp/codex_json.txt)

          echo "parse_failed=false" >> $GITHUB_OUTPUT
          echo "high_severity_count=$HIGH_COUNT" >> $GITHUB_OUTPUT
          echo "medium_severity_count=$MEDIUM_COUNT" >> $GITHUB_OUTPUT
          echo "recommendation=$RECOMMENDATION" >> $GITHUB_OUTPUT

          # For debugging
          echo "Codex found $HIGH_COUNT HIGH severity issues"
          echo "Codex found $MEDIUM_COUNT MEDIUM severity issues"
          echo "Recommendation: $RECOMMENDATION"

      - name: Post Codex Review as Comment
        uses: actions/github-script@v7
        env:
          CODEX_REVIEW: ${{ env.CODEX_OUTPUT }}
        with:
          script: |
            const codexOutput = process.env.CODEX_REVIEW;
            const highCount = ${{ steps.parse_results.outputs.high_severity_count }};
            const mediumCount = ${{ steps.parse_results.outputs.medium_severity_count }};

            let header = '';
            if (highCount > 0 && mediumCount > 0) {
              header = `## 🚨 Codex Review: ${highCount} HIGH, ${mediumCount} MEDIUM Severity Issue(s) Found`;
            } else if (highCount > 0) {
              header = `## 🚨 Codex Review: ${highCount} HIGH Severity Issue(s) Found`;
            } else if (mediumCount > 0) {
              header = `## ⚠️ Codex Review: ${mediumCount} MEDIUM Severity Issue(s) Found`;
            } else {
              header = `## ✅ Codex Review: No HIGH/MEDIUM Severity Issues`;
            }

            const body = `${header}

            <details>
            <summary>Full Codex Review</summary>

            ${codexOutput}

            </details>

            ---
            🤖 Reviewed by [Codex](https://github.com/openai/codex-action)
            `;

            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Label PR based on review
        uses: actions/github-script@v7
        with:
          script: |
            const parseFailed = '${{ steps.parse_results.outputs.parse_failed }}' === 'true';
            const highCount = parseInt('${{ steps.parse_results.outputs.high_severity_count }}', 10);
            const mediumCount = parseInt('${{ steps.parse_results.outputs.medium_severity_count }}', 10);
            const prNumber = context.payload.pull_request.number;

            if (parseFailed) {
              // Parse failed - require human review, do NOT auto-merge
              console.log('Parse failed - requiring human review');
              // Remove any stale ready-to-merge label to prevent auto-merge
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                name: 'ready-to-merge'
              }).catch(() => {}); // Ignore if label doesn't exist
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['needs-review', 'codex-parse-failed']
              });
            } else if (highCount > 0) {
              // HIGH severity found - needs fixes before merge
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['needs-fixes', 'codex-reviewed']
              });
            } else {
              // No HIGH severity - ready to merge (even if MEDIUM exists)
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['ready-to-merge', 'codex-reviewed']
              });
            }

      - name: Trigger Claude for Review (if HIGH or MEDIUM severity found)
        if: steps.parse_results.outputs.parse_failed != 'true' && (steps.parse_results.outputs.high_severity_count > 0 || steps.parse_results.outputs.medium_severity_count > 0)
        uses: actions/github-script@v7
        env:
          CODEX_REVIEW_OUTPUT: ${{ env.CODEX_OUTPUT }}
        with:
          script: |
            const highCount = parseInt('${{ steps.parse_results.outputs.high_severity_count }}', 10);
            const mediumCount = parseInt('${{ steps.parse_results.outputs.medium_severity_count }}', 10);

            // Check if this is already a retry (prevent infinite loops)
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number
            });

            const claudeFixCount = comments.filter(c =>
              c.body.includes('Attempting to address Codex') || c.body.includes('Reviewing Codex findings')
            ).length;

            if (claudeFixCount >= 1) {
              console.log('Already attempted fix once, requiring human intervention');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: '⚠️ **Max retry limit reached.** Claude already reviewed Codex findings once. Requires human review.'
              });
              return;
            }

            // Prepare instructions based on severity
            let instructions = '';
            if (highCount > 0 && mediumCount > 0) {
              instructions = `@claude-agent Codex found ${highCount} HIGH and ${mediumCount} MEDIUM severity issues.

**HIGH severity issues MUST be addressed.**
**MEDIUM severity issues:** Review them and address if you agree they are valid concerns. If you have a reasonable justification for not addressing a MEDIUM issue, explain your reasoning in a comment.`;
            } else if (highCount > 0) {
              instructions = `@claude-agent Codex found ${highCount} HIGH severity issue(s).

**You MUST address all HIGH severity issues.**`;
            } else {
              instructions = `@claude-agent Codex found ${mediumCount} MEDIUM severity issue(s).

**Review these issues** and address them if you agree they are valid concerns. If you have a reasonable justification for not addressing an issue, explain your reasoning in a comment. MEDIUM issues do not block merging.`;
            }

            // Get Codex output from environment variable (safe from injection)
            const codexOutput = process.env.CODEX_REVIEW_OUTPUT;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `${instructions}

            <details>
            <summary>Codex Review Details</summary>

            ${codexOutput}

            </details>

            **Instructions:**
            - HIGH severity issues MUST be addressed
            - MEDIUM severity issues: Review and address if valid, or explain why not
            - Commit any fixes to this branch

            🤖 Reviewing Codex findings (retry 1/1)
            `
            });
